USE mysql;

DELETE FROM user WHERE user='';

DROP DATABASE IF EXISTS test;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'DB_ROOT_PW';

CREATE DATABASE IF NOT EXISTS `DB_NAME`;

CREATE USER IF NOT EXISTS 'DB_USER_NAME'@'%' IDENTIFIED BY 'DB_USER_PW';

GRANT ALL PRIVILEGES ON `DB_NAME`.* TO 'DB_USER_NAME'@'%';

FLUSH PRIVILEGES;